---
###############################################################################
#                                                                             #
#                            WEBSITE CONFIGURATION                            #
#                                                                             #
###############################################################################

# --- base website settings ---

title: Vishal Dhanure
description: >-
  Homepage of Vishal Dhanure, an open source contributor  in the India .
url: "dhanurevishal2@gmail.com"
year: "2021"


# --- general settings ---

baseurl: ""  # the subpath of your site, e.g. /blog
git_repo: " "
favicon_path: "/static/favicon.ico"
logo_path: "/static/logo.jpg"

# Are you looking for new opportunities? Set hire_me to "true" if you want your
# LinkedIn to show on the nav bar and for boilerplate text on how to get in
# touch with me.
hire_me: true


# --- biography site information ---
# https://schema.org/

name: "Vishal Dhanure"
gender: "Male"
email: dhanurevishal2@gmail.com
blog: /blog
knows_about: >
  "Vishal Dhanure",
  "open source",
  "RIT",
  "Deogiri Insituite of Engineering and Management of studies , Aurangabad ",
  "Fedora Project",
  "Indian Open Source Community "

# -- social media --
github_username: Vi1234sh12
linkedin_url: vishaldhanure
twitter_username: VishalDhanure


# --- build settings ---

markdown: kramdown
permalink: pretty  # no .html extensions
sass:
  style: compressed
theme: minima


# --- exclusions ---
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - CNAME
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - LICENSE.txt
  - node_modules/
  - Rakefile
  - README.md
  - tmp
  - vendor
